version: "3.8"
services:

  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynet
    links:
      - "db:db"
    restart: always        
  
  db:
    image: cassandra
    networks:
      - mynet
    ports:
        - "9042:9042"


networks:
  mynet:
    driver: bridge
    